/** @type {import('tailwindcss').Config} */
export default {
	content: ['./src/**/*.{html,js,svelte,ts}'],
	darkMode: 'class',
	theme: {
		extend: {
			colors: {
				'primary': '#e1fdff',
				'primary-container': '#00f2ff',
				'primary-fixed': '#74f5ff',
				'primary-fixed-dim': '#00dbe7',
				'on-primary': '#00363a',
				'on-primary-fixed': '#002022',
				'on-primary-container': '#006a71',
				'on-primary-fixed-variant': '#004f54',
				'secondary': '#ffffff',
				'secondary-container': '#c3f400',
				'secondary-fixed': '#c3f400',
				'secondary-fixed-dim': '#abd600',
				'on-secondary': '#283500',
				'on-secondary-fixed': '#161e00',
				'on-secondary-container': '#556d00',
				'on-secondary-fixed-variant': '#3c4d00',
				'tertiary': '#fff6f1',
				'tertiary-container': '#ffd3af',
				'tertiary-fixed': '#ffdcc1',
				'tertiary-fixed-dim': '#ffb778',
				'on-tertiary': '#4c2700',
				'on-tertiary-fixed': '#2e1500',
				'on-tertiary-container': '#905000',
				'on-tertiary-fixed-variant': '#6c3a00',
				'surface': '#111318',
				'surface-dim': '#111318',
				'surface-bright': '#37393e',
				'surface-container-lowest': '#0c0e12',
				'surface-container-low': '#1a1c20',
				'surface-container': '#1e2024',
				'surface-container-high': '#282a2e',
				'surface-container-highest': '#333539',
				'surface-variant': '#333539',
				'surface-tint': '#00dbe7',
				'on-surface': '#e2e2e8',
				'on-surface-variant': '#b9cacb',
				'on-background': '#e2e2e8',
				'background': '#111318',
				'outline': '#849495',
				'outline-variant': '#3a494b',
				'error': '#ffb4ab',
				'error-container': '#93000a',
				'on-error': '#690005',
				'on-error-container': '#ffdad6',
				'inverse-surface': '#e2e2e8',
				'inverse-on-surface': '#2f3035',
				'inverse-primary': '#00696f',
			},
			spacing: {
				'touch-target-min': '72px',
				'base': '8px',
				'xs': '4px',
				'sm': '12px',
				'md': '24px',
				'lg': '48px',
				'safe-margin': '64px',
				'xl': '80px',
			},
			fontFamily: {
				'display-xl': ['Montserrat', 'sans-serif'],
				'display-lg': ['Montserrat', 'sans-serif'],
				'headline-xl': ['Anybody', 'sans-serif'],
				'headline-lg': ['Anybody', 'sans-serif'],
				'headline-md': ['Montserrat', 'sans-serif'],
				'stats-num': ['Montserrat', 'sans-serif'],
				'label-xl': ['Inter', 'sans-serif'],
				'label-caps': ['JetBrains Mono', 'monospace'],
				'body-lg': ['Inter', 'sans-serif'],
				'body-md': ['Inter', 'sans-serif'],
			},
			fontSize: {
				'display-xl': ['120px', { lineHeight: '110px', letterSpacing: '-0.04em', fontWeight: '900' }],
				'display-lg': ['80px', { lineHeight: '88px', letterSpacing: '-0.02em', fontWeight: '800' }],
				'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
				'headline-lg': ['48px', { lineHeight: '56px', fontWeight: '700' }],
				'headline-md': ['32px', { lineHeight: '40px', fontWeight: '700' }],
				'stats-num': ['64px', { lineHeight: '64px', fontWeight: '800' }],
				'label-xl': ['20px', { lineHeight: '24px', letterSpacing: '0.1em', fontWeight: '700' }],
				'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '600' }],
				'body-lg': ['24px', { lineHeight: '32px', fontWeight: '500' }],
				'body-md': ['18px', { lineHeight: '26px', fontWeight: '400' }],
			},
			borderRadius: {
				'DEFAULT': '0.25rem',
				'lg': '0.5rem',
				'xl': '0.75rem',
				'2xl': '16px',
				'3xl': '24px',
				'4xl': '32px',
				'full': '9999px',
			},
		},
	},
	plugins: [],
};
